version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "ip-down",
    "ip-down.d.dns.sh",
    "ip-up",
    "ip-up.d.dns.sh",
    "ipv6-down",
    "ipv6-up",
    "ipv6-up.d.iface-config.sh",
    "options",
    "ppp.systemd",
    "rebuild-list",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"
