version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "vsftpd.service",
    "vsftpd@.service",
    "vsftpd.socket",
    "ftpusers",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "adjust-usr-share-empty-to-var-empty.patch",
    "build-with-SSL-support.patch",
    "config-disable-anonymous-access-by-default.patch",
    "config-set-PAM-service-name-to-vsftpd.patch",
    "CVE-2015-1419.patch",
    "fix-build-with-openssl-1.1.patch",
    "fix-handle-AUTH_TLS-reply-to-FEAT-for-all-TLS-varian.patch",
    "fix-make-to-respect-distro-flags.patch",
    "fix-seccomp-rules.patch",
    "fix-ssl_tlsv-documentation-and-config-tunables.patch",
    "fix-setup_bio_callbacks-definition.patch",
]
SPDX-FileCopyrightText = "vsftpd contributors"
SPDX-License-Identifier = "GPL-2.0-only"
