#!/bin/bash

collections=`grep "name collection-" /usr/share/tlpkg/texlive.tlpdb | sed -e 's|name collection-||g;/texworks/d;/wintools/d' | tr "\n" " "`

sed '/_collections=/d' -i PKGBUILD
sed "/generate\ collections/a _collections=( ${collections})" -i "PKGBUILD"
