#!/bin/bash

pyver=$(pacman -S --print-format %v python | grep -oP '^[0-9]+\.[0-9]+')
exclude=('python2' 'python2-.*' 'pypy3\?' 'cython2' 'cuda' 'metasploit'
         'mysql-workbench' 'ntop' 'dia' 'ghidra' 'kross-interpreters'
         'kodi-gbm' 'kodi-wayland' 'kodi-x11')

{
pacman -Fq /usr/lib/python${pyver}/ | grep -v archlinuxcn | cut -d / -f 2
pacman -Fxq "\.cpython-${pyver/.}.pyc$" | grep -v archlinuxcn | cut -d / -f 2
sogrep all libpython${pyver}.so
ssh paw.archlinuxpower.org "parallel \"zstdgrep -q 'Py_Initialize\|PyInit_\|PyModule_Create2' {} && pacman -Qpq {}\" ::: /srv/http/repo.archlinuxpower.org/*/*/*.zst"
} | grep -xvf <(printf "%s\n" "${exclude[@]}") | sort -u
