[ruby-ffi-compiler]
source = "git"
git = "https://github.com/ffi/ffi-compiler.git"
# limited to 1.x as 2.x is a different gem:
# https://rubygems.org/gems/ffi-compiler
# https://rubygems.org/gems/ffi-compiler2
include_regex = "1.*"
