version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "systemd_service.diff",
    "CVE-2017-8779.diff",
    "rpcbind.conf",
    "tmpfiles.d",
    "sysusers.d"
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "rpcbind-sunrpc.patch",
]
SPDX-FileCopyrightText = "rpcbind contributors"
SPDX-License-Identifier = "BSD-3-Clause"
