version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "libssh2-1.11.1-CVE-2025-15661.patch",
    "libssh2-1.11.1-CVE-2026-55200.patch",
    "libssh2-1.11.1-CVE-2026-58050.patch",
]
SPDX-FileCopyrightText = "2009-2026 Daniel Stenberg and libssh2 contributors"
SPDX-License-Identifier = "BSD-3-Clause"
