[hunspell-en]
source = "regex"
# Official Hunspell Dictionaries: readme, en_US, en_CA, en_AU (2020.12.07)
#regex = "Official Hunspell Dictionaries: readme, en_US, en_CA, en_AU ([0-9.]+)"
# regex = "([0-9.]+)"
regex = "The latest release is: (\\d+.\\d+.\\d+)"
url = "http://wordlist.aspell.net/dicts/"
# ignored = "505050 10079"
