version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-Remove-citation-things.patch",
]
SPDX-FileCopyrightText = "parallel contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
