[tex-gyre-fonts]
source = "htmlparser"
url = "https://www.gust.org.pl/projects/e-foundry/tex-gyre/whole"
xpath = '//a[contains(text(), "OTF files")]/text()'
from_pattern = '.*(\d\.\d+).*'
to_pattern = '\1'
