version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".gitignore",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*sysusers.conf",
    "*.tmpfiles",
    "*tmpfiles.conf",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "yajl-0009-Allow-cmake-4.0.patch",
    "yajl-2.1.0-CVE-2017-16516.patch",
    "yajl-2.1.0-CVE-2022-24795.patch",
    "yajl-2.1.0-memory_leak.patch",
]
SPDX-FileCopyrightText = "yajl contributors"
SPDX-License-Identifier = "ISC"
