version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-seccomp-extend-syscalls-tested-on-Linux-6.1-with-gli.patch",
    "0001-tests-enable-drop_privileges-by-default-for-better-s.patch",
    "memcached.service.patch",
]
SPDX-FileCopyrightText = "memcached contributors"
SPDX-License-Identifier = "BSD-3-Clause"
