[xf86-video-amdgpu]
source = "gitlab"
gitlab = "xorg/driver/xf86-video-amdgpu"
host = "gitlab.freedesktop.org"
use_max_tag = true

include_regex = ".*xf86-video-amdgpu-.*"
prefix = "xf86-video-amdgpu-"
