version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "partimage-0.6.9-zlib-1.2.6.patch",
    "partimage-build-fix.patch",
    "use-SSLv3-by-default.patch",
]
SPDX-FileCopyrightText = "partimage contributors"
SPDX-License-Identifier = "TODO-Choose-a-license"
