#! /bin/bash

_date=$(date "+%Y%m%d")
ssh repos.archlinux.org mkdir -p /srv/ftp/other/packages/archlinux-appstream-data/$_date
scp -r export/data/arch/* repos.archlinux.org:/srv/ftp/other/packages/archlinux-appstream-data/$_date/
