#!/bin/bash

# general config
. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /opt/trinity/bin/tdm`
case "$1" in
   start)
      #Check for running tdm, start when not running
      stat_busy "Starting TDE Desktop Manager (tdm)"
      [ -z "$PID" ] && /opt/trinity/bin/tdm &> /dev/null
	   if [ $? -gt 0 ]; then
         stat_fail
      else
         echo $PID > /var/run/tdm.pid
         add_daemon tdm-trinity
         stat_done
      fi
      ;;
   stop)
      stat_busy "Stopping TDE Desktop Manager (tdm)"
      [ ! -z "$PID" ] && kill $PID &> /dev/null
      if [ $? -gt 0 ]; then
         stat_fail
      else
         rm_daemon tdm-trinity
         stat_done
      fi
      ;;
   restart)
      $0 stop
      sleep 1
      $0 start
      ;;
   *)
      echo "usage: $0 {start|stop|restart}"
      ;;
esac
exit 0
