[xfce4-screenshooter]
source = "git"
git = "https://gitlab.xfce.org/apps/xfce4-screenshooter.git"
prefix = "xfce4-screenshooter-"
include_regex = "xfce4-screenshooter-.*"
exclude_regex = "show.*|1.*"
