[hyphen]
# source = "regex"
# regex = "hyphen-([\\d.]+)\\."
# url = "https://sourceforge.net/projects/hunspell/files/Hyphen/"
source = "github"
github = "hunspell/hyphen"
use_max_tag = true
prefix = "v"
