[python-moto]
source = "pypi"
pypi = "moto"

# Custom attributes used by https://gitlab.com/yan12125/aur/
__custom_attributes__.group = "moto"
# Make sure py-partiql-parser constraints are applied
__custom_attributes__.extras = ["s3"]
__custom_attributes__.non_nvchecker = true
