[opencascade]
source = "git"
git = "https://github.com/Open-Cascade-SAS/OCCT.git"
prefix = "V"
from_pattern = "(\\d+)_(\\d+)_(\\d+)"
to_pattern = "\\1.\\2.\\3"
exclude_regex = ".*(pre|rc|alpha|beta).*"
