version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-Adapt-to-pkgconf-1.9.4.patch",
    "0002-Get-tests-to-pass.patch",
    "0003-Adapt-to-pkgconf-2.5.0.patch",
]
SPDX-FileCopyrightText = "perl-pkgconfig-libpkgconf contributors"
SPDX-License-Identifier = "TODO-Choose-a-license"
