version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-PR-579-net147-Fix-stack-overrun.patch",
    "0002-PR-571-jschleus-Some-zip-files-are-misclassified-as-data.patch",
    "0003-Fix-termios-handling.patch",
    "0004-glibc-2-42-tcgets2.patch",
]
SPDX-FileCopyrightText = "file contributors"
SPDX-License-Identifier = "LicenseRef-file"
