version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "syslog-ng-config.patch",
    "syslog-ng-do-not-install-python-venv.patch",
    "syslog-ng-systemd-integration.patch",
]
SPDX-FileCopyrightText = "syslog-ng contributors"
SPDX-License-Identifier = "0BSD"
