version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "d851fdd768b27c02b3fb786fd0987faddd279ece.patch",
    "scoped-mock-log.patch",
]
SPDX-FileCopyrightText = "abseil-cpp contributors"
SPDX-License-Identifier = "Apache-2.0"
