[gimp]
source = "git"
git = "https://gitlab.gnome.org/GNOME/gimp.git"
exclude_regex = "GIMP.*(\\_2\\_99|RC).*"
include_regex = "(GIMP\\_).*_(\\d+)?[02468]_(\\d+)"
from_pattern = "GIMP\\_(\\d+)\\_(\\d+)\\_(\\d+)"
to_pattern = "\\1.\\2.\\3"
