version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "010-python-lmdb-replace-pkg_resources-due-to-deprecation-in-setuptools-82.patch",
]
SPDX-FileCopyrightText = "python-lmdb contributors"
SPDX-License-Identifier = "OLDAP-2.8"
