version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "double-free-crash.patch",
    "fluidsynth-use-after-free.patch",
    "fluidsynth-volume.patch",
    "mikmod1.patch",
    "mikmod2.patch",
]
SPDX-FileCopyrightText = "sdl_mixer contributors"
SPDX-License-Identifier = "Zlib"
