version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "telepathy-logger-fix-doc.patch",
    "telepathy-logger-fix-tests.patch",
]
SPDX-FileCopyrightText = "telepathy-logger contributors"
SPDX-License-Identifier = "LGPL-2.1-or-later"
