post_install() {
  _arch=$(grep ^Architecture /etc/pacman.conf | awk '{print $3}')
  if [ "${_arch}" == 'powerpc64' ]; then
    echo '!! mold does not support ELFv2 on big-endian PPC64.'
    echo '!! it can however be used when crosscompuling.'
  fi
}

post_upgrade() {
  _arch=$(grep ^Architecture /etc/pacman.conf | awk '{print $3}')
  if [ "${_arch}" == 'powerpc64' ]; then
    echo '!! mold does not support ELFv2 on big-endian PPC64.'
    echo '!! it can however be used when crosscompuling.'
  fi
}
