version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "01_gcc6.patch",
    "02_hurd.patch",
    "03_CVE-2015-7747.patch",
    "04_clamp-index-values-to-fix-index-overflow-in-IMA.cpp.patch",
    "05_Always-check-the-number-of-coefficients.patch",
    "06_Check-for-multiplication-overflow-in-MSADPCM-decodeSam.patch",
    "07_Check-for-multiplication-overflow-in-sfconvert.patch",
    "08_Fix-signature-of-multiplyCheckOverflow.-It-returns-a-b.patch",
    "09_Actually-fail-when-error-occurs-in-parseFormat.patch",
    "10_Check-for-division-by-zero-in-BlockCodec-runPull.patch",
    "11_CVE-2018-13440.patch",
    "12_CVE-2018-17095.patch",
    "13_CVE-2019-13147.patch",
    "14_CVE-2022-24599.patch",
]
SPDX-FileCopyrightText = "audiofile contributors"
SPDX-License-Identifier = "Apache-2.0 OR GPL-2.0-or-later OR LGPL-2.1-or-later"
