post_install() {
  # Enable update by default
  systemctl --global enable xdg-user-dirs.service
}

pre_upgrade() {
  if (( $(vercmp $2 0.19-1) < 0)); then
    systemctl --global disable xdg-user-dirs-update.service
  fi
}

post_upgrade() {
  if (( $(vercmp $2 0.19-2) < 0)); then
    systemctl --global enable xdg-user-dirs.service
  fi
}

pre_remove() {
  systemctl --global disable xdg-user-dirs.service
}
