version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "abiword-3.0.0-librevenge.patch",
    "abiword-3.0.1-libwps-0.4.patch",
    "abiword-fix-appstream-data.patch",
]
SPDX-FileCopyrightText = "abiword contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
