[xfce4-smartbookmark-plugin]
source = "git"
git = "https://gitlab.xfce.org/panel-plugins/xfce4-smartbookmark-plugin.git"
prefix = "xfce4-smartbookmark-plugin-"
include_regex = "xfce4-smartbookmark-plugin-.*"
