version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "ostree-2023.1-use_fuse3.patch",
    "ostree-2025.2-fix-compilation.patch",
]
SPDX-FileCopyrightText = "ostree contributors"
SPDX-License-Identifier = "LGPL-2.0-or-later"
