post_install() {
   ldconfig &> /dev/null
   echo "Note that the tools provided by this package (assistant, designer,"
   echo "linguist, lrelease, lupdate, moc, qmake and qtconfig) have been"
   echo "renamed to tqt3<toolname> to ensure compatibility with Qt4 and should"
   echo "be run through new command scheme."
}

post_upgrade() {
   ldconfig &> /dev/null
}

post_remove() {
   ldconfig &> /dev/null
}

