[xf86-input-synaptics]
source = "gitlab"
gitlab = "xorg/driver/xf86-input-synaptics"
host = "gitlab.freedesktop.org"
use_max_tag = true

include_regex = ".*xf86-input-synaptics-.*"
prefix = "xf86-input-synaptics-"
