[goffice]
source = "git"
git = "https://gitlab.gnome.org/GNOME/goffice.git"
prefix = "GOFFICE_"
ignored = "GOFFICE_MERGE_FROM_HEAD_2004_OCT_19 GOFFICE_MERGE_FROM_HEAD_2004_NOV_16"
from_pattern = "_"
to_pattern = "."
