version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "useradd.defaults",
    "0001-Disable-replaced-tools-their-man-pages-and-PAM-integ.patch",
    "0002-Adapt-login.defs-for-PAM-and-util-linux.patch",
    "0003-Add-Arch-Linux-defaults-for-login.defs.patch",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"
